micronaut:
  application:
    name: wishListApi
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/wish_list_db
    driverClassName: org.postgresql.Driver
    db-type: postgres
    username: username
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      locations: classpath:db/migration